# This is a basic workflow to help you get started with Actions

name: Deploy to Beanstalk

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version_label:
        description: 'Version label for new Beanstalk version'     
        required: true
        default: '12345'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v1
      
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges.
        go-version: 1.16
#         # Whether to download only stable versions
#         stable: # optional, default is true
#         # Used to pull node distributions from go-versions.  Since there's a default, this is typically not supplied by the user.
#         token: # optional, default is ${{ github.token }
    - name: Building application
      run: go build -o app
      
    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'
    - name: Beanstalk Deploy
      # You may pin to the exact commit or the version.
      # uses: einaregilsson/beanstalk-deploy@ebe3476a4ce991d54336935e75e78dd9d86f9408
      uses: einaregilsson/beanstalk-deploy@v16
      with:
        # AWS Access Key
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID_CICD }}
        # AWS Secret Key
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_CICD }}
        # AWS Session Token when using temporary security credentials such as when assuming a role in AWS through STS
#         aws_session_token: # optional
        # AWS Region
        region: ap-northeast-1
        # Beanstalk application name
        application_name: bucket
        # Beanstalk environment name. If empty a version will be created but not deployed anywhere.
        environment_name: Bucket-env # optional
        # Version label for new Beanstalk version
        version_label: ${{ github.event.inputs.version_label }}
        # Version description for the new Beanstalk version
#         version_description: # optional
        # Zip file with the version to deploy. If skipped the action will deploy existing version.
        deployment_package: deploy.zip # optional
#         # If set to "true" then the action will deploy an existing version with the given version_label if it already exists, but otherwise create the version and deploy it.
#         use_existing_version_if_available: # optional
#         # Whether the action should wait for the deployment to finish and log status messages during the wait. Default is "true". If set to "false" the action will start the deployment on Beanstalk and then exit.
#         wait_for_deployment: # optional
#         # How many seconds to wait for the environment to return to Green state after deployment is finished. Default is 30 seconds.
#         wait_for_environment_recovery: # optional
